apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jmstechhome28/springapp-helm.git
    targetRevision: master
    path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: springapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
