apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jmstechhome28/springapp-helm.git
    targetRevision: master
    path: springapp
    helm:
      valueFiles:
        - values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: springapp
    syncPolicy:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
